In [3]:
import numpy as np 
a1=np.array([1,2,3])
a1,type(a1),a1.dtype

(array([1, 2, 3]), numpy.ndarray, dtype('int32'))

In [4]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
def identifier(objct):
    return print(f"a3's shape:{objct.shape}\n\na3's dimension:{objct.ndim}\n\na3's dtype:{objct.dtype}\n\na3's size(how many elements does it includes):{objct.size}\n\na3's type:{type(objct)}")

identifier(a3)


a3's shape:(2, 3, 3)

a3's dimension:3

a3's dtype:int32

a3's size(how many elements does it includes):18

a3's type:<class 'numpy.ndarray'>


In [24]:
import pandas as pd
a2=np.array([[1,2,3],[2,4,6]])
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  2  4  6

In [32]:
ar2=np.random.randint(1,10,size=(2,2))
ar2

array([[5, 3],
       [6, 5]])

In [41]:
np.random.seed(0)
a4=np.random.randint(10,size=(2,3,4,5))
a4,identifier(a4)

a3's shape:(2, 3, 4, 5)

a3's dimension:4

a3's dtype:int32

a3's size(how many elements does it includes):120

a3's type:<class 'numpy.ndarray'>


(array([[[[5, 0, 3, 3, 7],
          [9, 3, 5, 2, 4],
          [7, 6, 8, 8, 1],
          [6, 7, 7, 8, 1]],
 
         [[5, 9, 8, 9, 4],
          [3, 0, 3, 5, 0],
          [2, 3, 8, 1, 3],
          [3, 3, 7, 0, 1]],
 
         [[9, 9, 0, 4, 7],
          [3, 2, 7, 2, 0],
          [0, 4, 5, 5, 6],
          [8, 4, 1, 4, 9]]],
 
 
        [[[8, 1, 1, 7, 9],
          [9, 3, 6, 7, 2],
          [0, 3, 5, 9, 4],
          [4, 6, 4, 4, 3]],
 
         [[4, 4, 8, 4, 3],
          [7, 5, 5, 0, 1],
          [5, 9, 3, 0, 5],
          [0, 1, 2, 4, 2]],
 
         [[0, 3, 2, 0, 7],
          [5, 9, 0, 2, 7],
          [2, 9, 2, 3, 3],
          [2, 3, 4, 1, 2]]]]),
 None)

In [38]:
a4[:,:,:,:1]

array([[[[5],
         [9],
         [7],
         [6]],

        [[5],
         [3],
         [2],
         [3]],

        [[9],
         [3],
         [0],
         [8]]],


       [[[8],
         [9],
         [0],
         [4]],

        [[4],
         [7],
         [5],
         [0]],

        [[0],
         [5],
         [2],
         [2]]]])

In [44]:
a=np.random.randint(10,size=(2,3))
a=a.reshape((2,3,1))
b=np.random.randint(10,size=(2,3,3))

a*b

array([[[81, 18, 72],
        [36, 36, 54],
        [ 5, 30, 40]],

       [[56, 21, 14],
        [24, 48, 24],
        [48, 40, 56]]])

In [82]:
np.random.seed(42)
d1=np.random.randint(90,size=(5,3))
df1=pd.DataFrame(d1,columns=["Almond","Peanut","Cashew"],index=["Mon","Tue","Wed","Thur","Friday"])
d2=np.random.randint(30,size=(1,3))
df2=pd.DataFrame(d2,columns=["Almond","Peanut","Cashew"],index=["Price"])
df1,df2.T,np.dot(df2,df1.T)

(        Almond  Peanut  Cashew
 Mon         51      14      71
 Tue         60      20      82
 Wed         86      74      74
 Thur        87      23       2
 Friday      21      52       1,
         Price
 Almond     23
 Peanut     11
 Cashew     29,
 array([[3386, 3978, 4938, 2312, 1084]]))

In [69]:
df1

Almond  Peanut  Cashew
Mon         51      14      71
Tue         60      20      82
Wed         86      74      74
Thur        87      23       2
Friday      21      52       1

In [87]:
d1,d1.shape,d1[1,:]

(array([[51, 14, 71],
        [60, 20, 82],
        [86, 74, 74],
        [87, 23,  2],
        [21, 52,  1]]),
 (5, 3),
 array([60, 20, 82]))

In [77]:
d1.sort()
d1

array([[14, 51, 71],
       [20, 60, 82],
       [74, 74, 86],
       [ 2, 23, 87],
       [ 1, 21, 52]])

In [80]:
np.argsort(d1)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [89]:
np.argmin(d1[:,1]) #argmin gives us index of minimum value in the array

0

In [93]:
d1[2,:]

array([86, 74, 74])

In [92]:
np.argmax(d1[2,:]) #argmin gives us index of maximum value in the array

0

In [97]:
d1

array([[51, 14, 71],
       [60, 20, 82],
       [86, 74, 74],
       [87, 23,  2],
       [21, 52,  1]])

In [95]:
np.argmax(d1,axis=0)

array([3, 2, 1], dtype=int64)

In [96]:
np.argmax(d1,axis=1)

array([2, 2, 0, 0, 1], dtype=int64)